############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Learn" 
url = "learn/" 
weight = 3

[[main]]
name = "Resources"
url = "resources/"
weight = 4

[[main]]
name = "Community" 
url = "community/" 
weight = 5

[[main]]
weight = 6
name = "More"
hasChildren = true

[[main]]
parent = "More"
name = "Blog"
url = "blog/"

[[main]]
parent = "More"
name = "Contact"
url = "contact/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3
